# Generated by Django 4.1.5 on 2023-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_serial', models.CharField(default='i2NCwVhn0b1HUmZOa9KMe8NaT3JZ1lBHMbw5C5D0zoJk5u858jz9oj2q29v1', max_length=61, unique=True)),
                ('user1', models.CharField(max_length=255)),
                ('user2', models.CharField(max_length=255)),
            ],
        ),
    ]
