# Generated by Django 4.1.5 on 2023-01-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatusers_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='contacts',
            field=models.CharField(max_length=9999999),
        ),
    ]
