# Generated by Django 4.1.5 on 2023-01-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatusers_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='contacts',
            field=models.CharField(default=None, max_length=9999999),
        ),
    ]
