# Generated by Django 4.1.5 on 2023-01-31 20:45

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatusers_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='id_message',
            field=models.CharField(default=chat.models.create_id_serial, max_length=62, unique=True),
        ),
    ]
