# Generated by Django 4.1.5 on 2023-01-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessages_id_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='id_conversation',
            field=models.CharField(blank=True, max_length=61),
        ),
    ]
