# Generated by Django 4.1.5 on 2023-02-01 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_data_chatmessages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 23, 19)),
        ),
    ]
